import type { IntelMode, LayerCategory, LayerDefinition } from "@/core/types";
import { PALETTE } from "./theme";
import { MARKER_HUES as M } from "./marker-palette";

/** True when a layer belongs on the STRATEGIC or OSINT tab (ALL ignores this). */
export function layerInIntelMode(layer: LayerDefinition, mode: IntelMode): boolean {
  return layer.modes.includes(mode);
}

/**
 * The single source of truth for every data layer in Panoptes.
 *
 * Rendering, the left-rail toggles, clustering, filtering and source-health all
 * read from this registry. Adding a layer = adding one entry here (+ a static
 * file under public/geo or an /api route that returns normalized GeoJSON).
 *
 * `source.ref`:
 *   - static  -> file under /public/geo/<ref>
 *   - api     -> route under /api/<ref>
 *   - pmtiles -> tile URL (served from /tiles or object storage)
 */
export const LAYERS: LayerDefinition[] = [
  // ---------------------------------------------------------------- reference
  {
    id: "country-borders",
    name: "Country Borders",
    category: "reference",
    modes: ["curated", "osint"],
    kind: "polygon",
    marker: "ring",
    color: PALETTE.outline,
    renderer: "both",
    defaultEnabled: true,
    pickable: false,
    description: "Admin-0 sovereign boundaries (Natural Earth).",
    source: {
      kind: "static",
      ref: "country-borders.geojson",
      attribution: "Natural Earth",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "populated-places",
    name: "Populated Places",
    category: "reference",
    modes: ["curated", "osint"],
    kind: "point",
    marker: "square",
    color: M.outline,
    renderer: "both",
    defaultEnabled: false,
    minZoom: 3,
    description: "Major cities and towns (Natural Earth) — population context.",
    source: {
      kind: "static",
      ref: "populated-places.geojson",
      attribution: "Natural Earth",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "urban-areas",
    name: "Urban Areas",
    category: "reference",
    modes: ["curated", "osint"],
    kind: "polygon",
    marker: "ring",
    color: "#c4a35a",
    renderer: "flat",
    defaultEnabled: false,
    minZoom: 3,
    description: "Major urban extents (Natural Earth, scalerank ≤ 4). Population density context.",
    source: {
      kind: "static",
      ref: "urban-areas.geojson",
      attribution: "Natural Earth",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "tectonic-boundaries",
    name: "Tectonic Boundaries",
    category: "reference",
    modes: ["osint"],
    kind: "line",
    marker: "ring",
    color: "#c2550a",
    renderer: "both",
    defaultEnabled: false,
    description: "Tectonic plate boundaries (Bird 2003, Coffin et al.). Fault context for seismic and nuclear-site analysis.",
    source: {
      kind: "static",
      ref: "tectonic-boundaries.geojson",
      attribution: "PB2002 (Bird 2003) / global-tectonic-plates",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "volcanoes",
    name: "Volcanoes",
    category: "reference",
    modes: ["osint"],
    kind: "point",
    marker: "cross",
    color: M.orange,
    renderer: "both",
    defaultEnabled: false,
    description:
      "Holocene volcanoes (Smithsonian GVP / USGS). Context for seismic events — helps distinguish tectonic earthquakes from volcanic activity.",
    source: {
      kind: "static",
      ref: "volcanoes.geojson",
      attribution: "Smithsonian Global Volcanism Program / USGS",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "navareas",
    name: "NAVAREA Zones",
    category: "reference",
    modes: ["osint"],
    kind: "polygon",
    marker: "ring",
    color: PALETTE.intel,
    renderer: "both",
    defaultEnabled: false,
    description: "IMO/IHO NAVAREA maritime broadcast zones (NGA). 21 areas worldwide; pairs with Maritime Alerts layer.",
    source: {
      kind: "static",
      ref: "navareas.geojson",
      attribution: "NGA Maritime Safety Information",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "og-basins",
    name: "Oil & Gas Basins",
    category: "reference",
    modes: [],
    kind: "polygon",
    marker: "ring",
    color: "#8b6914",
    renderer: "flat",
    defaultEnabled: false,
    minZoom: 2,
    description: "Major oil & natural-gas sedimentary basins (OGIM). Strategic petroleum province context.",
    source: {
      kind: "static",
      ref: "og-basins.geojson",
      attribution: "OGIM v2 (EDF / MethaneSAT)",
      license: "CC BY 4.0",
      cadence: "static",
    },
  },

  // ----------------------------------------------------------------- maritime
  {
    id: "maritime-ais",
    name: "Maritime AIS",
    category: "maritime",
    modes: ["osint"],
    kind: "point",
    marker: "chevron",
    color: M.intel,
    renderer: "both",
    defaultEnabled: false,
    description:
      "Live AIS vessel positions near coasts (AISStream). Cargo/tanker (types 70–89) and military vessels (watchlist + type 35). Requires local relay: npm run ais:relay.",
    source: {
      kind: "worker",
      ref: "vessels",
      attribution: "AISStream.io",
      cadence: "live",
    },
  },
  {
    id: "maritime-alerts",
    name: "Maritime Alerts",
    category: "maritime",
    modes: ["osint"],
    kind: "point",
    marker: "triangle",
    color: M.alertOrange,
    renderer: "both",
    defaultEnabled: false,
    description:
      "In-force NGA navigational warnings (NAVAREA/HYDRO broadcast). Positioned at each warning's first coordinate.",
    source: {
      kind: "api",
      ref: "maritime-alerts",
      attribution: "NGA Maritime Safety Information",
      license: "Public Domain",
      cadence: "daily",
    },
  },
  {
    id: "major-ports",
    name: "Major Ports",
    category: "maritime",
    modes: ["curated"],
    kind: "point",
    marker: "square",
    color: M.portCyan,
    renderer: "both",
    defaultEnabled: false,
    description: "World Port Index — 3,600+ ports (NGA).",
    source: {
      kind: "static",
      ref: "major-ports.geojson",
      attribution: "NGA World Port Index",
      license: "Public Domain",
      cadence: "30d",
    },
  },
  {
    id: "rivers",
    name: "Major Rivers",
    category: "maritime",
    modes: ["curated"],
    kind: "line",
    marker: "ring",
    color: PALETTE.intel,
    renderer: "both",
    defaultEnabled: false,
    description: "Major navigable rivers and waterways (Natural Earth, scalerank ≤ 6).",
    source: {
      kind: "static",
      ref: "rivers.geojson",
      attribution: "Natural Earth",
      license: "Public Domain",
      cadence: "static",
    },
  },

  // ----------------------------------------------------------------- military
  {
    id: "military-bases",
    name: "Military Bases",
    category: "military",
    modes: ["curated"],
    kind: "point",
    marker: "triangle",
    color: M.gold,
    renderer: "both",
    defaultEnabled: true,
    description:
      "Global military installations merged from US Base Project (FY2024 Base Structure Report) and OSINT Military Base Map.",
    source: {
      kind: "static",
      ref: "military-bases.geojson",
      attribution:
        "US Base Project (usbaseproject.com) / OSINT Military Base Map",
      license: "Community / OSINT",
      cadence: "static",
    },
  },
  {
    id: "missile-silos",
    name: "Missile Silos",
    category: "military",
    modes: ["curated"],
    kind: "point",
    marker: "diamond",
    color: M.magenta,
    renderer: "both",
    defaultEnabled: false,
    description:
      "Historical ICBM silo and launch complex locations (community dataset). Decommissioned and operational sites.",
    source: {
      kind: "static",
      ref: "missile-silos.geojson",
      attribution: "Community / OSINT",
      license: "Community",
      cadence: "static",
    },
  },
  {
    id: "nuclear-test-sites",
    name: "Nuclear Test Sites",
    category: "military",
    modes: ["curated"],
    kind: "point",
    marker: "circle-split",
    color: M.ember,
    renderer: "both",
    defaultEnabled: false,
    description: "Historical nuclear weapon test and detonation sites worldwide.",
    source: {
      kind: "static",
      ref: "nuclear-test-sites.geojson",
      attribution: "Community / OSINT",
      license: "Community",
      cadence: "static",
    },
  },
  {
    id: "satellites",
    name: "Government & Military Satellites",
    category: "space",
    modes: ["osint"],
    kind: "point",
    marker: "hexagon",
    color: M.limeGreen,
    renderer: "both",
    defaultEnabled: false,
    description:
      "Live orbital positions for government & military satellites (UCS list, ~1,300 objects). Propagated client-side from CelesTrak TLE data. Updated every 30 seconds.",
    source: {
      kind: "worker",
      ref: "satellites",
      attribution: "CelesTrak / UCS Satellite Database",
      license: "Public Domain",
      cadence: "30s",
    },
  },
  {
    id: "launch-sites",
    name: "Launch & Spaceports",
    category: "space",
    modes: ["curated"],
    kind: "point",
    marker: "hexagon",
    color: M.intelSoft,
    renderer: "both",
    defaultEnabled: false,
    description: "Rocket launch sites and spaceports worldwide.",
    source: {
      kind: "static",
      ref: "launch-sites.geojson",
      attribution: "Wikipedia / compiled",
      cadence: "static",
    },
  },

  // ----------------------------------------------------------- infrastructure
  {
    id: "submarine-cables",
    name: "Submarine Cables",
    category: "infrastructure",
    modes: ["curated"],
    kind: "line",
    marker: "ring",
    color: PALETTE.intel,
    renderer: "both",
    defaultEnabled: false,
    description: "Global subsea telecom cable routes (TeleGeography).",
    source: {
      kind: "static",
      ref: "submarine-cables.geojson",
      attribution: "TeleGeography submarinecablemap.com",
      cadence: "7d",
    },
  },
  {
    id: "data-centers",
    name: "Data Centers",
    category: "infrastructure",
    modes: ["curated"],
    kind: "point",
    marker: "square",
    color: M.teal,
    renderer: "both",
    defaultEnabled: false,
    minZoom: 2,
    description:
      "Global data-center facilities (cloud / colocation). Overlapping city-centroid locations are jittered on a tight ring for visibility.",
    source: {
      kind: "static",
      ref: "data-centers.geojson",
      attribution: "Global Data Center Map (compiled)",
      cadence: "static",
    },
  },
  {
    id: "dams",
    name: "Dams & Reservoirs",
    category: "infrastructure",
    modes: ["curated"],
    kind: "point",
    marker: "circle-split",
    color: M.skyBlue,
    renderer: "both",
    defaultEnabled: false,
    description: "Large dams (GRanD) — critical infrastructure / water targets.",
    source: {
      kind: "static",
      ref: "dams.geojson",
      attribution: "GRanD / Global Dam Watch",
      cadence: "static",
    },
  },

  // ---------------------------------------------------------- mineral resources
  {
    // Formerly id "mineral-deposits" — renamed to match its actual dataset
    // (USGS critical minerals); "mineral-deposits" below is the broader file.
    id: "critical-minerals",
    name: "Critical Minerals",
    category: "mineral-resources",
    modes: ["curated"],
    kind: "point",
    marker: "diamond",
    color: M.tan,
    renderer: "both",
    defaultEnabled: false,
    description: "Critical-mineral deposits and mines (USGS).",
    source: {
      kind: "static",
      ref: "critical-minerals.geojson",
      attribution: "USGS",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "mineral-deposits",
    name: "Mineral Deposits",
    category: "mineral-resources",
    modes: ["curated"],
    kind: "point",
    marker: "diamond",
    color: M.rust,
    renderer: "both",
    defaultEnabled: false,
    description: "USGS major nonfuel mineral deposits worldwide (~3,200 sites).",
    source: {
      kind: "static",
      ref: "mineral-deposits.geojson",
      attribution: "USGS Mineral Resources Data System",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "iron-ore-mines",
    name: "Iron Ore Mines",
    category: "mineral-resources",
    modes: [],
    kind: "point",
    marker: "diamond",
    color: M.slate,
    renderer: "both",
    defaultEnabled: false,
    description: "Iron ore mines, operating or proposed (GEM). Steel supply-chain context.",
    source: {
      kind: "static",
      ref: "iron-ore-mines.geojson",
      attribution: "Global Energy Monitor (GEM)",
      license: "CC BY 4.0",
      cadence: "static",
    },
  },
  {
    id: "prio-diamonds",
    name: "Diamond Deposits",
    category: "mineral-resources",
    modes: [],
    kind: "point",
    marker: "square",
    color: M.ice,
    renderer: "both",
    defaultEnabled: false,
    description: "Diamond deposits and mines (PRIO). Conflict-resource context.",
    source: {
      kind: "static",
      ref: "prio-diamonds.geojson",
      attribution: "PRIO / Uppsala University",
      license: "Research use",
      cadence: "static",
    },
  },
  {
    id: "prio-gems",
    name: "Gem Deposits",
    category: "mineral-resources",
    modes: [],
    kind: "point",
    marker: "diamond",
    color: M.purple,
    renderer: "both",
    defaultEnabled: false,
    description: "Gemstone mining sites worldwide (PRIO).",
    source: {
      kind: "static",
      ref: "prio-gems.geojson",
      attribution: "PRIO / Uppsala University",
      license: "Research use",
      cadence: "static",
    },
  },
  // --------------------------------------------------------- plants & factories
  {
    id: "power-plants",
    name: "Power Plants (≥20 MW)",
    category: "plants-factories",
    modes: ["curated"],
    kind: "point",
    marker: "circle-split",
    color: M.amber,
    renderer: "both",
    defaultEnabled: false,
    description: "Global power plants ≥ 20 MW (WRI Global Power Plant Database). Markers color-coded by fuel type.",
    source: {
      kind: "static",
      ref: "power-plants.geojson",
      attribution: "World Resources Institute Global Power Plant Database",
      license: "CC BY 4.0",
      cadence: "static",
    },
  },
  {
    id: "nuclear-power-plants",
    name: "Nuclear Power Plants",
    category: "plants-factories",
    modes: ["curated"],
    kind: "point",
    marker: "circle-split",
    color: M.deepPink,
    renderer: "both",
    defaultEnabled: false,
    description: "Operating and under-construction nuclear reactors (GEM Nuclear). Filter: status = operating or construction.",
    source: {
      kind: "static",
      ref: "nuclear-power-plants.geojson",
      attribution: "Global Energy Monitor (GEM)",
      license: "CC BY 4.0",
      cadence: "static",
    },
  },
  {
    id: "iron-steel-plants",
    name: "Iron & Steel Plants",
    category: "plants-factories",
    modes: [],
    kind: "point",
    marker: "square",
    color: M.steelGrey,
    renderer: "both",
    defaultEnabled: false,
    description: "Global iron and steel production facilities (GEM). Non-retired plants only.",
    source: {
      kind: "static",
      ref: "iron-steel-plants.geojson",
      attribution: "Global Energy Monitor (GEM)",
      license: "CC BY 4.0",
      cadence: "static",
    },
  },
  {
    id: "ammonia-plants",
    name: "Ammonia Plants",
    category: "plants-factories",
    modes: [],
    kind: "point",
    marker: "square",
    color: M.moss,
    renderer: "both",
    defaultEnabled: false,
    description: "Global ammonia production facilities (GEM). Dual-use: key fertilizer and industrial chemical precursor.",
    source: {
      kind: "static",
      ref: "ammonia-plants.geojson",
      attribution: "Global Energy Monitor (GEM)",
      license: "CC BY 4.0",
      cadence: "static",
    },
  },

  // --------------------------------------------------------------- oil & gas
  {
    id: "undiscovered-oil-gas",
    name: "Undiscovered Oil & Gas",
    category: "oil-gas",
    modes: ["curated"],
    kind: "polygon",
    marker: "ring",
    color: PALETTE.gold,
    renderer: "flat",
    defaultEnabled: false,
    description: "USGS assessed undiscovered petroleum provinces.",
    source: {
      kind: "static",
      ref: "undiscovered-oil-gas.geojson",
      attribution: "USGS",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "og-fields",
    name: "Oil & Gas Fields",
    category: "oil-gas",
    modes: ["curated"],
    kind: "point",
    marker: "ring",
    color: M.brown,
    renderer: "both",
    defaultEnabled: false,
    description: "Major oil & gas extraction fields (GEM field-level data). Excludes cancelled/abandoned.",
    source: {
      kind: "static",
      ref: "og-fields.geojson",
      attribution: "Global Energy Monitor (GEM)",
      license: "CC BY 4.0",
      cadence: "static",
    },
  },
  {
    id: "gas-pipelines",
    name: "Gas Pipelines",
    category: "oil-gas",
    modes: ["curated"],
    kind: "line",
    marker: "ring",
    color: PALETTE.gold,
    renderer: "flat",
    defaultEnabled: false,
    minZoom: 3,
    description: "Operating natural-gas pipelines (GEM GGIT, operating status). Large dataset — loads on zoom.",
    source: {
      kind: "static",
      ref: "gas-pipelines.geojson",
      attribution: "Global Energy Monitor (GEM GGIT)",
      license: "CC BY 4.0",
      cadence: "static",
    },
  },
  {
    id: "offshore-platforms",
    name: "Offshore Platforms",
    category: "oil-gas",
    modes: ["curated"],
    kind: "point",
    marker: "circle-split",
    color: M.seaGreen,
    renderer: "both",
    defaultEnabled: false,
    minZoom: 2,
    description: "Offshore oil & gas platforms (DoE + OGIM, removed platforms excluded).",
    source: {
      kind: "static",
      ref: "offshore-platforms.geojson",
      attribution: "US DoE / OGIM (EDF)",
      license: "Public Domain / CC BY 4.0",
      cadence: "static",
    },
  },
  {
    id: "lng-terminals",
    name: "LNG Terminals",
    category: "oil-gas",
    modes: [],
    kind: "point",
    marker: "square",
    color: M.violet,
    renderer: "both",
    defaultEnabled: false,
    description: "LNG import/export terminals (DoE + OGIM + GEM aggregated). Chokepoint-sensitive energy logistics.",
    source: {
      kind: "static",
      ref: "lng-terminals.geojson",
      attribution: "US DoE / OGIM / GEM",
      license: "Public Domain / CC BY 4.0",
      cadence: "static",
    },
  },
  {
    id: "petroleum-terminals",
    name: "Petroleum Terminals",
    category: "oil-gas",
    modes: [],
    kind: "point",
    marker: "square",
    color: M.deepBlue,
    renderer: "both",
    defaultEnabled: false,
    description: "Petroleum storage & distribution terminals (OGIM).",
    source: {
      kind: "static",
      ref: "petroleum-terminals.geojson",
      attribution: "OGIM v2 (EDF / MethaneSAT)",
      license: "CC BY 4.0",
      cadence: "static",
    },
  },
  {
    id: "refineries",
    name: "Oil Refineries",
    category: "oil-gas",
    modes: [],
    kind: "point",
    marker: "circle-split",
    color: M.goldenrod,
    renderer: "both",
    defaultEnabled: false,
    description: "Crude-oil refineries worldwide (DoE + OGIM aggregated). Non-inactive facilities.",
    source: {
      kind: "static",
      ref: "refineries.geojson",
      attribution: "US DoE / OGIM (EDF)",
      license: "Public Domain / CC BY 4.0",
      cadence: "static",
    },
  },

  // ---------------------------------------------------------------- conflict
  {
    id: "historical-conflicts",
    name: "Historical Conflicts",
    category: "conflict",
    modes: ["curated"],
    kind: "point",
    marker: "diamond",
    color: M.lightGold,
    renderer: "both",
    defaultEnabled: false,
    description:
      "Militarized interstate disputes & incidents (COW MIDLOC 2.1, 1816–2014). Violet = dispute-level (MIDLOCA); red = incident-level (MIDLOCI). Overlapping locations are jittered for visibility.",
    approxLocation: true,
    source: {
      kind: "static",
      ref: "historical-conflicts.geojson",
      attribution: "Correlates of War (COW) / MIDLOC 2.1",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "water-conflicts",
    name: "Water Conflicts",
    category: "conflict",
    modes: ["curated"],
    kind: "point",
    marker: "diamond",
    color: M.deepRed,
    renderer: "both",
    defaultEnabled: false,
    description:
      "Historical & current water-related conflicts (Pacific Institute). Overlapping locations are jittered for visibility.",
    source: {
      kind: "static",
      ref: "water-conflicts.geojson",
      attribution: "Pacific Institute Water Conflict Chronology",
      cadence: "annual",
    },
  },
  {
    id: "conflict-events",
    name: "Conflict Events (media)",
    category: "conflict",
    modes: ["osint"],
    kind: "point",
    marker: "diamond",
    color: M.coralRed,
    renderer: "both",
    defaultEnabled: false,
    description:
      "Media-reported battle / attack / airstrike clusters (GDELT, last 24h). Markers colored by coverage tone (red gradient). Overlapping geocodes are jittered for visibility. Media signal, not verified events.",
    source: {
      kind: "api",
      ref: "gdelt",
      attribution: "GDELT Project",
      cadence: "15min",
    },
  },

  // ----------------------------------------------------------------- hazards
  {
    id: "earthquakes",
    name: "Earthquakes",
    category: "hazards",
    modes: ["osint"],
    kind: "point",
    marker: "ring",
    color: M.amberRing,
    renderer: "both",
    defaultEnabled: false,
    description: "M2.5+ seismic events (USGS, 7-day feed). Use the 1 DAY / 7 DAYS toggle bottom-left to change the visible window. Weak signal for large explosions.",
    source: {
      kind: "api",
      ref: "earthquakes",
      attribution: "USGS Earthquake Hazards Program",
      license: "Public Domain",
      cadence: "hourly",
    },
  },
  {
    id: "earthquakes-major",
    name: "Major Earthquakes",
    category: "hazards",
    modes: ["osint"],
    kind: "point",
    marker: "ring",
    color: M.crimson,
    renderer: "both",
    defaultEnabled: false,
    sizeScale: 1.7,
    description: "USGS 'significant' earthquakes, last 7 days — high-impact events only. Always shows the full 7-day window. Enable alongside Earthquakes for context.",
    source: {
      kind: "api",
      ref: "earthquakes-significant",
      attribution: "USGS Earthquake Hazards Program",
      license: "Public Domain",
      cadence: "hourly",
    },
  },
  {
    id: "fires",
    name: "Active Fires (thermal)",
    category: "hazards",
    modes: ["osint"],
    kind: "point",
    marker: "cross",
    color: M.alert,
    renderer: "both",
    defaultEnabled: false,
    description: "VIIRS active-fire detections, last 24h (NASA FIRMS). Weak signal for battle activity.",
    source: {
      kind: "api",
      ref: "fires",
      attribution: "NASA FIRMS",
      cadence: "15min",
    },
  },

  // ------------------------------------------------------------- humanitarian
  {
    id: "disasters",
    name: "Disaster Events",
    category: "humanitarian",
    modes: ["osint"],
    kind: "point",
    marker: "cross",
    color: M.reliefCyan,
    renderer: "both",
    defaultEnabled: true,
    approxLocation: true,
    description: "Active humanitarian disasters (ReliefWeb).",
    source: {
      kind: "api",
      ref: "reliefweb",
      attribution: "ReliefWeb (OCHA)",
      cadence: "daily",
    },
  },

  // ----------------------------------------------------------------- aviation
  {
    id: "military-airports",
    name: "Military Airports",
    category: "aviation",
    modes: ["curated"],
    kind: "point",
    marker: "square",
    color: M.airfieldGold,
    renderer: "both",
    defaultEnabled: false,
    description:
      "Military airfields and air bases worldwide (OurAirports). Select an airport with a valid ICAO code for METAR / SIGMET in the right panel.",
    source: {
      kind: "static",
      ref: "military-airports.geojson",
      attribution: "OurAirports (ourairports.com)",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "military-flights",
    name: "Military Flights",
    category: "aviation",
    modes: ["osint"],
    kind: "point",
    marker: "chevron",
    color: M.aviationGreen,
    renderer: "both",
    defaultEnabled: false,
    description: "Live military ADS-B aircraft (IntelSky + adsb.lol, registry-enriched). OpenSky gap-fill when configured.",
    source: {
      kind: "api",
      ref: "flights",
      attribution: "IntelSky / adsb.lol",
      license: "ODbL",
      cadence: "60s",
    },
  },

  {
    id: "railroads",
    name: "Railroads",
    category: "infrastructure",
    modes: ["curated"],
    kind: "line",
    marker: "ring",
    color: "#b08cc9", // muted violet — distinct from rivers (cyan) and roads (grey)
    renderer: "both",
    defaultEnabled: false,
    minZoom: 2,
    description: "Global trunk rail network (Natural Earth, scalerank ≤ 6). Military logistics context.",
    source: {
      kind: "static",
      ref: "railroads.geojson",
      attribution: "Natural Earth",
      license: "Public Domain",
      cadence: "static",
    },
  },

  // -------------------------------------------------------------- information
  {
    id: "internet-outages",
    name: "Internet Outages",
    category: "information",
    modes: ["osint"],
    kind: "point",
    // Distinct from Active Fires (cross/alert): outages read as a "split" signal.
    marker: "circle-split",
    color: M.hotPink,
    renderer: "both",
    defaultEnabled: false,
    description: "Internet traffic anomalies & outages (Cloudflare Radar).",
    source: {
      kind: "api",
      ref: "outages",
      attribution: "Cloudflare Radar",
      cadence: "30min",
    },
  },
];

export const LAYERS_BY_ID: Record<string, LayerDefinition> = Object.fromEntries(
  LAYERS.map((l) => [l.id, l]),
);

export const CATEGORY_ORDER: LayerCategory[] = [
  "conflict",
  "military",
  "aviation",
  "maritime",
  "space",
  "infrastructure",
  "mineral-resources",
  "oil-gas",
  "plants-factories",
  "hazards",
  "humanitarian",
  "information",
  "reference",
];

export const CATEGORY_LABELS: Record<LayerCategory, string> = {
  conflict: "Conflict & Violence",
  military: "Military & Strategic",
  aviation: "Aviation",
  maritime: "Maritime",
  space: "Space & Orbital",
  infrastructure: "Critical Infrastructure",
  "mineral-resources": "Mineral Resources",
  "oil-gas": "Oil & Gas",
  "plants-factories": "Plants & Factories",
  hazards: "Hazards & Weak Signals",
  humanitarian: "Humanitarian",
  information: "Information Environment",
  reference: "Reference & Context",
};

export function defaultLayerState(): Record<string, boolean> {
  return Object.fromEntries(
    LAYERS.filter((l) => !l.placeholder).map((l) => [l.id, l.defaultEnabled]),
  );
}
