import type { LayerCategory, LayerDefinition } from "@/core/types";
import { PALETTE } from "./theme";

/**
 * The single source of truth for every data layer in Panoptes.
 *
 * Rendering, the left-rail toggles, clustering, filtering and source-health all
 * read from this registry. Adding a layer = adding one entry here (+ a static
 * file under public/geo or an /api route that returns normalized GeoJSON).
 *
 * `source.ref`:
 *   - static  -> file under /public/geo/<ref>
 *   - api     -> route under /api/<ref>
 *   - pmtiles -> tile URL (served from /tiles or object storage)
 */
export const LAYERS: LayerDefinition[] = [
  // ---------------------------------------------------------------- reference
  {
    id: "tectonic-boundaries",
    name: "Tectonic Boundaries",
    category: "reference",
    mode: "curated",
    kind: "line",
    marker: "ring",
    color: "#c2550a", // rust/burnt-orange — distinct from country borders (grey)
    renderer: "both",
    defaultEnabled: false,
    description: "Tectonic plate boundaries (Bird 2003, Coffin et al.). Fault context for seismic and nuclear-site analysis.",
    source: {
      kind: "static",
      ref: "tectonic-boundaries.geojson",
      attribution: "PB2002 (Bird 2003) / global-tectonic-plates",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "navareas",
    name: "NAVAREA Zones",
    category: "reference",
    mode: "curated",
    kind: "polygon",
    marker: "ring",
    color: PALETTE.intel,
    renderer: "both",
    defaultEnabled: false,
    description: "IMO/IHO NAVAREA maritime broadcast zones (NGA). 21 areas worldwide; pairs with Maritime Alerts layer.",
    source: {
      kind: "static",
      ref: "navareas.geojson",
      attribution: "NGA Maritime Safety Information",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "urban-areas",
    name: "Urban Areas",
    category: "reference",
    mode: "osint",
    kind: "polygon",
    marker: "ring",
    color: "#c4a35a", // sand/amber — distinct from grey layers, reflects built-up density
    renderer: "flat",
    defaultEnabled: false,
    minZoom: 3,
    description: "Major urban extents (Natural Earth, scalerank ≤ 4). Population density context.",
    source: {
      kind: "static",
      ref: "urban-areas.geojson",
      attribution: "Natural Earth",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "country-borders",
    name: "Country Borders",
    category: "reference",
    mode: "curated",
    kind: "polygon",
    marker: "ring",
    color: PALETTE.outline,
    renderer: "both",
    defaultEnabled: true,
    description: "Admin-0 sovereign boundaries (Natural Earth).",
    source: {
      kind: "static",
      ref: "country-borders.geojson",
      attribution: "Natural Earth",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "populated-places",
    name: "Populated Places",
    category: "reference",
    mode: "osint",
    kind: "point",
    marker: "square",
    color: PALETTE.outline,
    renderer: "both",
    defaultEnabled: false,
    minZoom: 3,
    description: "Major cities and towns (Natural Earth) — population context.",
    source: {
      kind: "static",
      ref: "populated-places.geojson",
      attribution: "Natural Earth",
      license: "Public Domain",
      cadence: "static",
    },
  },

  // ----------------------------------------------------------------- military
  {
    id: "military-bases",
    name: "Military Bases",
    category: "military",
    mode: "curated",
    kind: "point",
    marker: "triangle",
    color: PALETTE.gold,
    renderer: "both",
    defaultEnabled: true,
    description: "Global military installations (community + OSM derived).",
    source: {
      kind: "static",
      ref: "military-bases.geojson",
      attribution: "OSM / community KML",
      license: "ODbL / community",
      cadence: "static",
    },
  },
  {
    id: "satellites",
    name: "Government & Military Satellites",
    category: "space",
    mode: "curated",
    kind: "point",
    marker: "hexagon",
    color: PALETTE.intelSoft,
    renderer: "both",
    defaultEnabled: false,
    description:
      "Live orbital positions for government & military satellites (UCS list, ~1,300 objects). Propagated client-side from CelesTrak TLE data. Updated every 30 seconds.",
    source: {
      kind: "worker",
      ref: "satellites",
      attribution: "CelesTrak / UCS Satellite Database",
      license: "Public Domain",
      cadence: "30s",
    },
  },
  {
    id: "launch-sites",
    name: "Launch & Spaceports",
    category: "space",
    mode: "curated",
    kind: "point",
    marker: "hexagon",
    color: PALETTE.intelSoft,
    renderer: "both",
    defaultEnabled: false,
    description: "Rocket launch sites and spaceports worldwide.",
    source: {
      kind: "static",
      ref: "launch-sites.geojson",
      attribution: "Wikipedia / compiled",
      cadence: "static",
    },
  },

  // ----------------------------------------------------------- infrastructure
  {
    id: "major-ports",
    name: "Major Ports",
    category: "maritime",
    mode: "curated",
    kind: "point",
    marker: "square",
    color: PALETTE.intel,
    renderer: "both",
    defaultEnabled: false,
    description: "World Port Index — 3,600+ ports (NGA).",
    source: {
      kind: "static",
      ref: "major-ports.geojson",
      attribution: "NGA World Port Index",
      license: "Public Domain",
      cadence: "30d",
    },
  },
  {
    id: "rivers",
    name: "Major Rivers",
    category: "maritime",
    mode: "curated",
    kind: "line",
    marker: "ring",
    color: PALETTE.intel,
    renderer: "both",
    defaultEnabled: false,
    description: "Major navigable rivers and waterways (Natural Earth, scalerank ≤ 6).",
    source: {
      kind: "static",
      ref: "rivers.geojson",
      attribution: "Natural Earth",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "maritime-alerts",
    name: "Maritime Alerts",
    category: "maritime",
    mode: "osint",
    kind: "point",
    // triangle=warning; alert red. Distinct from Military Bases (triangle+gold).
    marker: "triangle",
    color: PALETTE.alert,
    renderer: "both",
    defaultEnabled: false,
    description:
      "In-force NGA navigational warnings (NAVAREA/HYDRO broadcast). Positioned at each warning's first coordinate.",
    source: {
      kind: "api",
      ref: "maritime-alerts",
      attribution: "NGA Maritime Safety Information",
      license: "Public Domain",
      cadence: "daily",
    },
  },
  {
    id: "submarine-cables",
    name: "Submarine Cables",
    category: "infrastructure",
    mode: "curated",
    kind: "line",
    marker: "ring",
    color: PALETTE.intel,
    renderer: "both",
    defaultEnabled: false,
    description: "Global subsea telecom cable routes (TeleGeography).",
    source: {
      kind: "static",
      ref: "submarine-cables.geojson",
      attribution: "TeleGeography submarinecablemap.com",
      cadence: "7d",
    },
  },
  {
    id: "data-centers",
    name: "Data Centers",
    category: "infrastructure",
    mode: "osint",
    kind: "point",
    marker: "square",
    color: PALETTE.intelSoft,
    renderer: "both",
    defaultEnabled: false,
    minZoom: 2,
    description: "Global data-center facilities (cloud / colocation).",
    source: {
      kind: "static",
      ref: "data-centers.geojson",
      attribution: "Global Data Center Map (compiled)",
      cadence: "static",
    },
  },
  {
    id: "dams",
    name: "Dams & Reservoirs",
    category: "infrastructure",
    mode: "curated",
    kind: "point",
    marker: "circle-split",
    color: PALETTE.intel,
    renderer: "both",
    defaultEnabled: false,
    description: "Large dams (GRanD) — critical infrastructure / water targets.",
    source: {
      kind: "static",
      ref: "dams.geojson",
      attribution: "GRanD / Global Dam Watch",
      cadence: "static",
    },
  },

  // ---------------------------------------------------------- mineral resources
  {
    id: "mineral-deposits",
    name: "Critical Minerals",
    category: "mineral-resources",
    mode: "osint",
    kind: "point",
    marker: "diamond",
    color: PALETTE.gold,
    renderer: "both",
    defaultEnabled: false,
    description: "Critical-mineral deposits and mines (USGS).",
    source: {
      kind: "static",
      ref: "mineral-deposits.geojson",
      attribution: "USGS",
      license: "Public Domain",
      cadence: "static",
    },
  },
  // --------------------------------------------------------------- oil & gas
  {
    id: "undiscovered-oil-gas",
    name: "Undiscovered Oil & Gas",
    category: "oil-gas",
    mode: "osint",
    kind: "polygon",
    marker: "ring",
    color: PALETTE.gold,
    renderer: "flat",
    defaultEnabled: false,
    description: "USGS assessed undiscovered petroleum provinces.",
    source: {
      kind: "static",
      ref: "undiscovered-oil-gas.geojson",
      attribution: "USGS",
      license: "Public Domain",
      cadence: "static",
    },
  },

  // ---------------------------------------------------------------- conflict
  {
    id: "water-conflicts",
    name: "Water Conflicts",
    category: "conflict",
    mode: "curated",
    kind: "point",
    marker: "diamond",
    color: PALETTE.alert,
    renderer: "both",
    defaultEnabled: false,
    description: "Historical & current water-related conflicts (Pacific Institute).",
    source: {
      kind: "static",
      ref: "water-conflicts.geojson",
      attribution: "Pacific Institute Water Conflict Chronology",
      cadence: "annual",
    },
  },
  {
    id: "conflict-events",
    name: "Conflict Events (media)",
    category: "conflict",
    mode: "osint",
    kind: "point",
    marker: "diamond",
    color: PALETTE.alert,
    renderer: "both",
    defaultEnabled: false,
    description:
      "Media-reported battle / attack / airstrike clusters (GDELT, last 24h). Markers colored by coverage tone (red=highly negative → green=positive). Media signal, not verified events.",
    source: {
      kind: "api",
      ref: "gdelt",
      attribution: "GDELT Project",
      cadence: "15min",
    },
  },

  // ----------------------------------------------------------------- hazards
  {
    id: "earthquakes",
    name: "Earthquakes",
    category: "hazards",
    mode: "osint",
    kind: "point",
    marker: "ring",
    color: PALETTE.gold,
    renderer: "both",
    defaultEnabled: false,
    description: "M2.5+ seismic events (USGS, 7-day feed). Use the 1 DAY / 7 DAYS toggle bottom-left to change the visible window. Weak signal for large explosions.",
    source: {
      kind: "api",
      ref: "earthquakes",
      attribution: "USGS Earthquake Hazards Program",
      license: "Public Domain",
      cadence: "hourly",
    },
  },
  {
    id: "earthquakes-major",
    name: "Major Earthquakes",
    category: "hazards",
    mode: "osint",
    kind: "point",
    marker: "ring",
    color: PALETTE.alert,
    renderer: "both",
    defaultEnabled: false,
    // Larger red rings so significant events stand out over the M2.5+ layer.
    sizeScale: 1.7,
    description: "USGS 'significant' earthquakes, last 7 days — high-impact events only. Always shows the full 7-day window. Enable alongside Earthquakes for context.",
    source: {
      kind: "api",
      ref: "earthquakes-significant",
      attribution: "USGS Earthquake Hazards Program",
      license: "Public Domain",
      cadence: "hourly",
    },
  },
  {
    id: "fires",
    name: "Active Fires (thermal)",
    category: "hazards",
    mode: "osint",
    kind: "point",
    marker: "cross",
    color: PALETTE.alert,
    renderer: "both",
    defaultEnabled: false,
    description: "VIIRS active-fire detections, last 24h (NASA FIRMS). Weak signal for battle activity.",
    source: {
      kind: "api",
      ref: "fires",
      attribution: "NASA FIRMS",
      cadence: "15min",
    },
  },

  // ------------------------------------------------------------- humanitarian
  {
    id: "disasters",
    name: "Disaster Events",
    category: "humanitarian",
    mode: "curated",
    kind: "point",
    marker: "cross",
    color: PALETTE.intelSoft,
    renderer: "both",
    defaultEnabled: true,
    // ReliefWeb only geolocates to the country centroid; markers are jittered to
    // de-overlap, so exact coordinates are synthetic and must not be shown.
    approxLocation: true,
    description: "Active humanitarian disasters (ReliefWeb).",
    source: {
      kind: "api",
      ref: "reliefweb",
      attribution: "ReliefWeb (OCHA)",
      cadence: "daily",
    },
  },

  // ----------------------------------------------------------------- aviation
  {
    id: "military-airports",
    name: "Military Airports",
    category: "aviation",
    mode: "curated",
    kind: "point",
    marker: "square",
    color: PALETTE.gold,
    renderer: "both",
    defaultEnabled: false,
    description:
      "Military airfields and air bases worldwide (OurAirports). ident = ICAO/local code.",
    source: {
      kind: "static",
      ref: "military-airports.geojson",
      attribution: "OurAirports (ourairports.com)",
      license: "Public Domain",
      cadence: "static",
    },
  },
  {
    id: "military-flights",
    name: "Military Flights",
    category: "aviation",
    mode: "osint",
    kind: "point",
    marker: "chevron",
    color: PALETTE.friendly,
    renderer: "both",
    defaultEnabled: false,
    description: "Live military ADS-B aircraft (adsb.lol /v2/mil).",
    source: {
      kind: "api",
      ref: "flights",
      attribution: "adsb.lol",
      license: "ODbL",
      cadence: "60s",
    },
  },

  // ------------------------------------------------ Tier B (PMTiles, on-demand)
  {
    id: "roads",
    name: "Road Network",
    category: "infrastructure",
    mode: "osint",
    kind: "line",
    marker: "ring",
    color: PALETTE.outline,
    renderer: "flat",
    defaultEnabled: false,
    minZoom: 4,
    description: "Global road network (GRIP/gROADS). Heavy layer — vector tiles, loads on zoom.",
    source: {
      kind: "pmtiles",
      ref: "/tiles/roads.pmtiles",
      attribution: "GRIP4 / gROADS (GLOBIO, NASA)",
      cadence: "static",
    },
  },
  {
    id: "oil-gas-pipelines",
    name: "Oil & Gas Pipelines",
    category: "oil-gas",
    mode: "osint",
    kind: "line",
    marker: "ring",
    color: PALETTE.gold,
    renderer: "flat",
    defaultEnabled: false,
    minZoom: 3,
    description: "Global oil & gas pipeline network (OGIM / EDF). Vector tiles.",
    source: {
      kind: "pmtiles",
      ref: "/tiles/oil-gas-pipelines.pmtiles",
      attribution: "OGIM v2 (EDF / MethaneSAT)",
      cadence: "static",
    },
  },
  {
    id: "oil-gas-wells",
    name: "Oil & Gas Wells",
    category: "oil-gas",
    mode: "osint",
    kind: "point",
    marker: "circle-split",
    color: PALETTE.gold,
    renderer: "flat",
    defaultEnabled: false,
    minZoom: 5,
    description: "Global oil & gas wells (OGIM / EDF). Very dense — vector tiles.",
    source: {
      kind: "pmtiles",
      ref: "/tiles/oil-gas-wells.pmtiles",
      attribution: "OGIM v2 (EDF / MethaneSAT)",
      cadence: "static",
    },
  },
  {
    id: "reservoirs",
    name: "Reservoirs",
    category: "infrastructure",
    mode: "osint",
    kind: "polygon",
    marker: "ring",
    color: PALETTE.intel,
    renderer: "flat",
    defaultEnabled: false,
    minZoom: 3,
    description: "Large reservoirs (GRanD). Vector tiles.",
    source: {
      kind: "pmtiles",
      ref: "/tiles/reservoirs.pmtiles",
      attribution: "GRanD / Global Dam Watch",
      cadence: "static",
    },
  },

  // -------------------------------------------------------------- information
  {
    id: "internet-outages",
    name: "Internet Outages",
    category: "information",
    mode: "osint",
    kind: "point",
    // Distinct from Active Fires (cross/alert): outages read as a "split" signal.
    marker: "circle-split",
    color: PALETTE.alert,
    renderer: "both",
    defaultEnabled: false,
    description: "Internet traffic anomalies & outages (Cloudflare Radar).",
    source: {
      kind: "api",
      ref: "outages",
      attribution: "Cloudflare Radar",
      cadence: "30min",
    },
  },
];

export const LAYERS_BY_ID: Record<string, LayerDefinition> = Object.fromEntries(
  LAYERS.map((l) => [l.id, l]),
);

export const CATEGORY_ORDER: LayerCategory[] = [
  "conflict",
  "military",
  "aviation",
  "maritime",
  "space",
  "infrastructure",
  "mineral-resources",
  "oil-gas",
  "plants-factories",
  "hazards",
  "humanitarian",
  "information",
  "reference",
];

export const CATEGORY_LABELS: Record<LayerCategory, string> = {
  conflict: "Conflict & Violence",
  military: "Military & Strategic",
  aviation: "Aviation",
  maritime: "Maritime",
  space: "Space & Orbital",
  infrastructure: "Critical Infrastructure",
  "mineral-resources": "Mineral Resources",
  "oil-gas": "Oil & Gas",
  "plants-factories": "Plants & Factories",
  hazards: "Hazards & Weak Signals",
  humanitarian: "Humanitarian",
  information: "Information Environment",
  reference: "Reference & Context",
};

export function defaultLayerState(): Record<string, boolean> {
  return Object.fromEntries(LAYERS.map((l) => [l.id, l.defaultEnabled]));
}
